### ISSUE TITLE
[bug]: Module '"@strapi/blocks-react-renderer"' has no exported member 'BlocksContent'

### ISSUE THREAD

**Issue by thiphariel** [strapi/blocks-react-renderer#14]
### What version of `@strapi/blocks-react-renderer` are you using?

- Nextjs 14.0.4
- Nodejs lts/iron (20.10.x)
- React 18+
- `@strapi/blocks-react-renderer@latest` (1.0.0-beta.0)

### What's Wrong?

VSCode returning that the module isn't exporting any type `BlocksContent` as shown on the readme

### To Reproduce

Paste the following import into a project with the plugin installed : 

```js
import {
  BlocksRenderer,
  type BlocksContent,
} from '@strapi/blocks-react-renderer'
```

### Expected Behaviour

The module should export a usable type I guess?

**Comment by remidej** [comment]
Sorry about that, I merged a PR to main that included readme changes (#13), but haven't released that change yet

**Comment by thiphariel** [comment]
Hey, all good! Feel free to close the issue whenever you publish it then! And thank you :-)

**Comment by remidej** [comment]
I just published it, you can try version `beta.1` :)

**Comment by thiphariel** [comment]
Hi again!

I don't think that beta.1 includes your PR sadly, when you look at the `index.ts` on that specific tag : https://github.com/strapi/blocks-react-renderer/blob/v1.0.0-beta.1/src/index.ts

The main branch does though.

Sorry for the extra work haha!

**Comment by remidej** [comment]
Indeed I forgot to pull the changes before creating the release 🤡 

Thanks for the tip! It should normally be okay this time with beta.2

**Comment by thiphariel** [comment]
Perfect! Thank you again :D
