### ISSUE TITLE
[feat]: render in a react server component

### ISSUE THREAD

**Issue by martijnmichel** [strapi/blocks-react-renderer#33]
### A clear and concise description of what the feature is

Render blocks on the server, for instance with nextjs server components.

### Why should this feature be included?

It does not make sense to create a client component for some blog content to render?

### Please provide an example for how this would work

at a first glance of the code only remove the context from blog renderer should do the trick

**Comment by benmgreene** [comment]
Hi there - was this enhancement actually completed? Having difficulty seeing where it was done. Thanks!

**Comment by martijnmichel** [comment]
I'm not sure, it's been a while since I posted. Actually I remember duplicating this codebase and fixing the problem internally. If you like I can freshen up my mind and lookup how I've fixed it.

**Comment by ancashoria** [comment]
@martijnmichel it would be nice to have it render in a server component.

**Comment by martijnmichel** [comment]
I copied the codebase of this repo and changed the defaultComponents manually..
